### ISSUE TITLE
Automate app deployment through GitHub

### ISSUE THREAD

**Issue by estherkim** [ampproject/amp-github-apps#410]
Currently GitHub apps are deployed manually using a local repository, which means a deployed app could be out of sync with what's in master.

cc/ @ampproject/wg-infra

**Comment by rcebulko** [comment]
To make this happen, I think we might want some sort of simple UI for setting/configuring the environment(s) for each app (since it's obviously not checked into GitHub). A simple dashboard showing each app with commands to stop, restart, deploy from HEAD/a commit, and edit `.env` variables would probably be really useful

**Comment by danielrozenberg** [comment]
I think the `npm run deploy-tag` feature that @rcebulko developed is a good enough, we don't really need a UI for this :)
@estherkim can we close?
