### ISSUE TITLE
Fix contributors count badge on amphtml

### ISSUE THREAD

**Issue by estherkim** [ampproject/amp-github-apps#475]
The contributors badge count is different than the repo's contributor count
![image](https://user-images.githubusercontent.com/44627152/65555599-0bf0d180-defb-11e9-9f76-facaf5716de1.png)
and
![image](https://user-images.githubusercontent.com/44627152/65555606-101cef00-defb-11e9-8a71-e40342a256c7.png)

cc/ @ampproject/wg-infra

**Comment by rcebulko** [comment]
The shields.io endpoint being used includes anon contributors. See [here](https://shields.io/category/activity) and [here](https://stackoverflow.com/questions/36410357/github-v3-api-list-contributors). I assume this was intentional; if it should be the same as the tab, I think it should be removed altogether.

**Comment by estherkim** [comment]
Hmm I see. I think it's redundant and vote to remove.

**Comment by estherkim** [comment]
cc @sudhanemani if you want to look at this also!

**Comment by rsimha** [comment]
Good catch @estherkim!

Badge is being removed in https://github.com/ampproject/amphtml/pull/24964. Root cause of inaccuracy is https://github.com/badges/shields/issues/764.

**Comment by rcebulko** [comment]
Closed by https://github.com/ampproject/amphtml/pull/25816

**Comment by rcebulko** [comment]
(mistakenly closed, confused this for a similar issue)

**Comment by rcebulko** [comment]
Closed by https://github.com/ampproject/amphtml/pull/24964
