### ISSUE TITLE
[owners] Post-approval comments seen as rejecting reviews

### ISSUE THREAD

**Issue by choumx** [ampproject/amp-github-apps#478]
I noticed that https://github.com/ampproject/amphtml/pull/24730 state "needs approval" for a file despite the requester already having approved the PR. Might be because new commits were added?

```
Current Coverage
- [NEEDS APPROVAL] src/service/extensions-impl.js (requested: jridgewell)
- test/unit/test-extensions.js (choumx)
```

https://github.com/ampproject/amphtml/pull/24730/checks?check_run_id=236887665

**Comment by rcebulko** [comment]
This is an unforeseen side-effect of GitHub considering post-approval comments to be "reviews" (which was unfortunately not documented in the API being used, but was documented in the GraphQL API). So in this case, it saw Justin's approval, then it saw he commented afterwards, and it appeared as if he changed his review from approval to "comment". The fix for this is pending approval in #477 and should be deployed by end-of-week.
