### ISSUE TITLE
Update logging in `build-system` to mirror `amphtml` conventions

### ISSUE THREAD

**Issue by rcebulko** [ampproject/amp-github-apps#607]
Back-reference to #606

**Comment by danielrozenberg** [comment]
Is this done?

**Comment by rcebulko** [comment]
I don't believe so, no. I'm not very familiar with amphtml logging conventions though

**Comment by rcebulko** [comment]
@rsimha Should this still be open?

**Comment by rsimha** [comment]
> @rsimha Should this still be open?

Yes, it should. I requested this cleanup in order to make Travis logs for `amp-github-apps` more readable. (See comparison screenshots below.)

I can think of two things that will greatly improve log readability:
- Use colors / blank lines to indicate when one test suite ends and another begins (we can reuse `amphtml`'s [timing methods](https://github.com/ampproject/amphtml/blob/6d7ccee0e30987d546459d170d24c49d9419bddb/build-system/pr-check/utils.js#L149-L186) to [run each task in its shell](https://github.com/ampproject/amphtml/blob/6d7ccee0e30987d546459d170d24c49d9419bddb/build-system/pr-check/utils.js#L198-L209))
- Silence logs in the passing case (test suites that pass shouldn't print copious logs, and tests with unexpected errors / warnings should be failures)

[`amphtml`](https://travis-ci.org/ampproject/amphtml/jobs/643540260):

![image](https://user-images.githubusercontent.com/26553114/73399001-77391e80-42b4-11ea-8acc-d6e5a7f4b76c.png)

[`amp-github-apps`](https://travis-ci.org/ampproject/amp-github-apps/builds/643373522):

![image](https://user-images.githubusercontent.com/26553114/73399045-8cae4880-42b4-11ea-808e-02e349172b19.png)

**Comment by rsimha** [comment]
For posterity, new logging looks like this:

![112196261-3b13fc00-8be1-11eb-8608-1eabe8f340c1](https://user-images.githubusercontent.com/26553114/112202403-baa4c980-8be7-11eb-9ef8-c7794b64d787.png)
