### ISSUE TITLE
Project bundle-size-chart is not a GitHub app

### ISSUE THREAD

**Issue by rcebulko** [ampproject/amp-github-apps#659]
I didn't notice #611 when it was submitted, but it added the [bundle size chart](https://amp-bundle-size-chart.appspot.com/) to this repository. The bundle size chart is not a GitHub app; it is a relatively simple server with cron tasks to update the data. This should probably not be a top-level project in this repository, and I think we don't want this repo to become a dumping ground for small projects when we're not sure where else to put them.

I feel like either this endpoint should be embedded in the Express server built into the Probot instance run by the bundle size app, or it should be spun off into a separate project or repo somewhere. It's also worth noting that, by running it as a standalone app with its own instances and storage, this costs on the order of $40/mo just to serve a static page.

This may be a good candidate for a serverless setup, since its only function is to A) receive cron requests to update a cloud storage blob and B) serve that blob to HTTP requests. @ampproject/wg-infra may benefit from gaining some familiarity with serverless setups, given that many of our services are stateless reactions to webhooks and other events.

Thoughts?

**Comment by danielrozenberg** [comment]
You're right that I used this repo as a "dumping ground" for this project. I don't think a single extra project in here is a big deal, but if we do end up with 2-3 of these different types of projects, it'll be worth considering a new repo.

I don't want to integrate it into the Probot app because this is a separate project that is less scrutinized and not as important. If you want to learn how to do serverless setups, that could be a fun side project!

As for the cost - Google is providing the AppEngine instance as part of the infra package, it doesn't really cost anyone $40/mo :)
