### ISSUE TITLE
[OwnerBot] Exclude some WG members for PR reviews

### ISSUE THREAD

**Issue by lannka** [ampproject/amp-github-apps#747]
The use cases are
1) there are some wg-ads members that are not 100% committed to review PRs.
2) when some members are OOO, they can exclude themselves from reviewers.

Let me know what you think, or this is something already supported.

**Comment by rcebulko** [comment]
I see too potential ways to do this with the current setup.

1. This could be achieved by creating a team like `ampproject/no-review-wg-ads` and adding it as an owner with `requestReviews: false`; this could be cumbersome if the WG is in many owners files
2. Alternately, you could create a team like `wg-ads-reviewers` and use that for owners files, especially if you the remaining WG members probably won't need to provide owners approval at all.

Here's why I think these workarounds make the most sense. Any way of ''opting out'' from a Team owner group would either need to be done in every owners file (which is cumbersome), or in some top-level list of ''users to exclude from review requests''. Assuming we don't want to replicate the list of users everywhere, we'd go with the second approach.

Now we'd have to have some sort of list mapping working groups to members of those groups that shouldn't be requested. In other words, a list of non-reviewers. This is effectively what a team/group alias would be, but a group won't need a commit to update membership.

I see two partial features/syntactic sugar that could possibly be worth considering. One is to incorporate some team name structure the bot can look for, for example if a team name `ampproject/no-review-{{teamName}}` exists, automatically exclude them from review requests to `ampproject/{{teamName}}`.

The second is to add a syntactic sugar `exclude: ['ampproject/no-review-wg-ads']`, which would be the same as just adding `{name: 'ampproject/no-review-wg-ads', requestReviews: false}`. Since this is already supported, I would lean against the `exclude` option, but listing the consideration here for completeness.

**Comment by lannka** [comment]
I took the suggestion 2. Neat solution.
that I could easily change membership on GH w/o a code change.

**Comment by rcebulko** [comment]
Glad it worked out so easily for you and the team!
