### ISSUE TITLE
Owners bot posts really long comments for refactoring PRs

### ISSUE THREAD

**Issue by danielrozenberg** [ampproject/amp-github-apps#852]
Example: https://github.com/ampproject/amphtml/pull/28234#issuecomment-625757883

There should be _some_ cutoff, although what it is exactly needs to be discussed

**Comment by rcebulko** [comment]
In the above example PR, there were 468 changed files. I wonder if it makes more sense to have a file count cutoff instead of a cutoff on # of notification recipients? I can see cases where a lot of people are listed for certain directories/files, and a relatively small PR could touch a number of important areas. However, any PR with more than, say, 200 files is almost definitely a refactor/Prettier change.

**Comment by danielrozenberg** [comment]
Right, that makes sense. I vaguely remember that @rsimha dealt with a similar issue when adding Prettier for the first time - maybe he got some input

**Comment by rsimha** [comment]
> In the above example PR, there were 468 changed files.

https://github.com/ampproject/amphtml/pull/28234#issuecomment-625757883 was extra long because https://github.com/ampproject/amphtml/pull/28234 wasn't properly rebased and mistakenly pulled in hundreds of older commits.

> I vaguely remember that @rsimha dealt with a similar issue

Yep, it had to do with the length of the checkRun output, not the notification comment. See #761 

> I can see cases where a lot of people are listed for certain directories/files, and a relatively small PR could touch a number of important areas. However, any PR with more than, say, 200 files is almost definitely a refactor/Prettier change.

Right, we don't want to violate the contract of `notify: true`. E.g. If a large refactor PR introduces a breaking change to a particular extension, the owners of that extension would want the notification so they can review their part.

- Given that large refactors are rare (e.g. there have been a total of two large `prettier` refactors since mid 2019), I think a legitimate option is to leave things as they are.
- Alternatively, you could truncate notification comments that are larger than a certain threshold by listing just the directories that were changed instead of every single file.
- A third option is to not post a comment if the file count exceeds a threshold, but this will violate the `notify` contract.


I'll leave the final call to @rcebulko 😃

**Comment by danielrozenberg** [comment]
> * Alternatively, you could truncate notification comments that are larger than a certain threshold by listing just the directories that were changed instead of every single file.

Building on this, we can have a relatively low threshold for the number of files to list (~12) and if there are more than that number of files, just list all the owners in the comment and tell them to go see the check output for full details

**Comment by rcebulko** [comment]
I like the above suggestion with a reasonable cutoff. That said, given the rarity mentioned by `@rsimha` and the low severity/impact, I'm labeling this a P3 for now. It's a great candidate for a fixit or a Good First Issue for a new team member or intern :eyes:
