### ISSUE TITLE
Error reporter filters out relevant PR change

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amp-github-apps#903]
Re: https://github.com/ampproject/amphtml/issues/28888

The actual cause of the bug is https://github.com/ampproject/amphtml/pull/28781, which is the following lines in the bug report:

```
    at scheduleUnlayout (extensions/amp-list/0.1/amp-list.js:1073:12)
    at toArray (extensions/amp-list/0.1/amp-list.js:1072:10)
```

I'd hope to see the relevant PR in the `notes` section, but they're filtered out.

**Comment by rcebulko** [comment]
This happened because the `messageHeadline` field returned by GraphQL was truncated:

```json
{
  "commit": {
    "changedFiles": 2,
    "committedDate": "2020-06-13T02:33:12Z",
    "messageHeadline": "🐛 [amp-list] Call scheduleUnlayout when amp-list container is updated…",
    "author": {
      "name": "Kevin Dwan",
      "user": { "login": "krdwan" }
    }
  },
  "startingLine": 1072,
  "endingLine": 1074
},
```

Annoyingly, GraphQL already randomly times out sometimes for this query. The solution will be to either fetch and parse the full commit message, or join across the `associatedPullRequests` connection. The latter would be ideal, but may increase timeouts. Still, probably better than all the extra bytes that would be included in the full commit messages for each blame.

I'll throw a PR together with an updated query.
